import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-sans`}>
        <div className="max-w-[1500px] mx-auto">
          <Header />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
